### ISSUE TITLE
Please suggest how you would like to receive patches for application nginx

### ISSUE THREAD

**Issue by james-nesbitt** [iler/alpine-nginx-pagespeed#1]
I would like to submit a build patch for a Drupall application specific nginx instance, but I think that you probably don't want it merged into this image.  Will you create child images for various purposes?
- php-fpm application?
- backend proxy?
- multi-backend proxy?

If so, then it makes sense for me to wait to submit patches there.  I may open a pull request, only to demo that php-fpm application requirements.

**Comment by iler** [comment]
Yes, child images for different purposes for various purposes is the way I've been thinking. Any objections for this?

**Comment by james-nesbitt** [comment]
no problems with that idea
