### ISSUE TITLE
Improvements suggestions

### ISSUE THREAD

**Issue by wernight** [iler/alpine-nginx-pagespeed#2]
In your Dockerfile:
- Single ENV block to limit the number of layers like `ENV foo=123 bar=456` (can be on multiple lines with `\`).
- Install `ca-certificates` instead of using `--no-check-certificate`
- Do `apk add --no-cache -t .build-deps package1 package2 && ... && apk del .build-deps` cleaner than runtime_pkgs
- `set -x` at the beginning of the long command to see each command in when building.
- Indent multiline commands

**Comment by iler** [comment]
Thanks a lot for the feedback and improvements! All of these make sense and will merge your pull request in.
