### ISSUE TITLE
Redirect outputs

### ISSUE THREAD

**Issue by wernight** [iler/alpine-nginx-pagespeed#4]
Just like official Nginx on Alpine, I'd redirect to stdout:

```
RUN
  # forward request and error logs to docker log collector
 && ln -sf /dev/stdout /var/log/nginx/access.log \
 && ln -sf /dev/stderr /var/log/nginx/error.log
```

**Comment by iler** [comment]
Our goal is to have this image as minimal base image as possible and then for every use case (app, proxy, sslterminator etc) customise this with Dockerfile. So even though this is a good practise I would rather not set this here but set it the images that base on this image.

**Comment by wernight** [comment]
It's up to you but it's a standard good Docker practice as you said. I think all official containers do that, and most popular containers do it as well. That snippet comes from the official [Nginx Alpine Docker image](https://hub.docker.com/_/nginx/) (and that only because Nginx doesn't support simple logging directly to stdout/stderr).

**Comment by james-nesbitt** [comment]
I agree on setting all output to stdout/stderr, but I am not sure why nginx.conf cannot be used to direct output there, instead of symlinking.

@iler I agree with the idea, but you have 2 choices (IMHO):
1. symlink default nginx conf paths to stdout / stderr
2. modify nginx.conf to set error_log & access_log to point to /dev/stderr & /dev/stdout

I have nginx dumping stderr, but I think that perhaps I have not got stdout working (haven't really verified it)

Check the nginx.conf that I dumped on top of your install : https://github.com/james-nesbitt/shareddockertools/blob/master/wundertools/docker/alpine-nginx-pagespeed/etc/nginx/conf/nginx.conf#L21

**Comment by wernight** [comment]
I don't know why indeed. If I remember I tried the configuration but it failed and then I copied what Nginx team did and it worked. Personally having a default `nginx.conf` or `ln -s` is similar: They both aim to achieve the same goal and are both valid.

**Comment by james-nesbitt** [comment]
maybe nginx fixed this.  Iler just pointed me to this: http://nginx.org/en/docs/ngx_core_module.html#error_log

"error_log stderr"  seems an allowed setting.

**Comment by wernight** [comment]
See linked bug. It looks like `ln -s` is a better option, and I'd tend to agree as I had that case (of invalid config).

**Comment by james-nesbitt** [comment]
that looks pretty authoritative to me

**Comment by james-nesbitt** [comment]
https://github.com/iler/alpine-nginx-pagespeed/issues/5 has an attempt to do as recommended.

one weird thing is: I thought that I'd have to remove the existing /var/log/[error|access].log, but there was no file there.  Can there be any permissions issues with stdout/stderr?

**Comment by wernight** [comment]
I would not bother removing the existing file, just force the link. I think I did it on my fork without issue. May be directory `/var/log/nginx` isn't existing?

I have exactly and same as you exept one or two more plugins:

```
# forward request and error logs to docker log collector
ln -sf /dev/stdout /var/log/nginx/access.log && \
ln -sf /dev/stderr /var/log/nginx/error.log
```

**Comment by wernight** [comment]
Ah you're building from source, so it's:

    # forward request and error logs to docker log collector
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

**Comment by james-nesbitt** [comment]
@wernight https://github.com/iler/alpine-nginx-pagespeed/pull/5 is now merged.

**Comment by iler** [comment]
I think we can close this now as it's configured as instructed in here https://github.com/nginxinc/docker-nginx/issues/87
