### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by bazaglia** [iler/alpine-nginx-pagespeed#7]
Thanks for sharing. I just noticies two issues.

1) This red message keeps repeating all the time during compilation and I don't know why.

```
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
```

2) You may remove line 75 of Dockerfile (https://github.com/iler/alpine-nginx-pagespeed/blob/715be75af92f8c061471cc72a19ee17df59a7b82/Dockerfile#L75) as you're reseting prefix in line 96 (https://github.com/iler/alpine-nginx-pagespeed/blob/715be75af92f8c061471cc72a19ee17df59a7b82/Dockerfile#L96)

**Comment by iler** [comment]
1) Yes it repeats but it does not affect the operation of the image. Thing is that when you are building things from source and using multiple different sources you will get similar warnings.

2) Thanks for this. Will remove the first one.

Also you should note that the development of this image has been moved to https://github.com/wunderkraut/alpine-nginx-pagespeed
